on: [push]

name: Maven Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '*'
          distribution: 'adopt'
      - name: Install Maven
        run: sudo apt-get install maven
      - name: Run Maven test
        run: mvn test
